baseURL = "http://ayushvj08.github.io/"
languageCode = "en-us"
title = "Ayush Vijayant"
theme = "m10c"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Ayush"
  description = "Welcome to my hugo blogSite."
  avatar = "ayush1.jpg"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/ayushvj08"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/AyushVijayant"

    [params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"